#!/bin/zsh

local bare_prompt=${(%):-(${PR_USER})- }

unset PR_RUBY
if [[ -n "$rvm_version" ]]; then
  local rvm_color="$PR_GREEN"
  local rvm_version=`rvm current`
  if [[ "$rvm_version" == "system" ]]; then
    rvm_color="${PR_RED}"
  fi
  bare_prompt="${bare_prompt}-[${rvm_version}]"
  PR_RUBY="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${rvm_color}${rvm_version}${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

PR_GIT=`parse_git_branch`
if [[ -n "$PR_GIT" ]]; then
  local GIT_STATUS=""
  local GIT_STATUS_BARE=""
  __add_status() {
    eval "GIT_STATUS=\"$GIT_STATUS$1$2\""
    eval "GIT_STATUS_BARE=\"$GIT_STATUS_BARE$2\""
  }
  
  local git_status=`git status --porcelain`

  local num_staged=`echo $git_status    | grep "^\w."  | wc -l | xargs`
  local num_deleted=`echo $git_status   | grep "^.D"   | wc -l | xargs`
  local num_changed=`echo $git_status   | grep "^.\w"  | wc -l | xargs`
  local num_conflicts=`echo $git_status | grep "^U."   | wc -l | xargs`
  local num_untracked=`echo $git_status | grep "^??"   | wc -l | xargs`
  
  [[ num_staged    -ne 0 ]] && __add_status ${PR_LIGHT_GREEN}  "✚${num_staged}"
  [[ num_changed   -ne 0 ]] && __add_status ${PR_LIGHT_YELLOW} "Δ${num_changed}"
  [[ num_deleted   -ne 0 ]] && __add_status ${PR_LIGHT_RED}    "✖${num_deleted}"
  [[ num_conflicts -ne 0 ]] && __add_status ${PR_RED}          "!${num_conflicts}"
  [[ num_untracked -ne 0 ]] && __add_status ${PR_NO_COLOR}     "…${num_untracked}"
  [[ -z $GIT_STATUS ]]      && __add_status ${PR_GREEN}        "✔"
  
  local ahead=`git to-push | wc -l | xargs`
  GIT_AHEAD=`[[ $ahead -ne 0 ]] && echo "↑${ahead}"`
      
  bare_prompt="${bare_prompt}-[${PR_GIT}${GIT_AHEAD}|${GIT_STATUS_BARE}]"
  
  PR_GIT="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${PR_GREEN}${PR_GIT}${GIT_AHEAD}|${GIT_STATUS}${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

PR_EMAIL=''
mail -e &> /dev/null
if [[ $? -eq 0 ]]; then
  bare_prompt="${bare_prompt}-[*]"
  PR_EMAIL="${PR_LIGHT_BLACK}${PR_SHIFT_IN}${PR_HBAR}${PR_SHIFT_OUT}[${PR_LIGHT_YELLOW}E${PR_LIGHT_BLACK}]${PR_NO_COLOR}"
fi

local TERMWIDTH
(( TERMWIDTH = ${COLUMNS} - 1 ))
local promptsize=${#${bare_prompt}}
PR_FILLBAR="\${(l.(($TERMWIDTH - $promptsize))..${PR_HBAR}.)}"

if [[ "$USER" == "root" ]]; then
  PR_USER_COLOR="${PR_RED}"
fi

